---
- name: Playbook to create custom EE
  hosts: localhost
  gather_facts: false
  collections:
    - infra.ee_utilities
    - infra.controller_configuration
  vars:
    # For ansible.cfg generation
    # For controller configuration definition
    ee_update_base_images: false
    ee_builder_image: quay.io/ansible/ansible-builder:latest
    ee_base_image: quay.io/ansible/ansible-runner:latest
    ee_version: 2
    ee_reg_credential: Automation Hub Container Registry
    ee_list:
      - name: custom_ee
        alt_name: Custom EE
        tag: 1-11-21-2
        bindep:
          - python38-devel [platform:rpm compile]
          - podman [platform:rpm]
        python:
          - pytz  # for schedule_rrule lookup plugin
          - python-dateutil>=2.7.0  # schedule_rrule
          - awxkit  # For import and export modules
          - ansible-lint[lock]==6.11.0
          - ansible-runner==2.3.1
          - ansible-builder
          - molecule==4.0.4
          - molecule-podman==2.0.3
          - paramiko==2.12.0  # https://github.com/ansible/creator-ee/issues/140
          - jmespath==1.0.1  # needed for json_query module
        collections:
          - name: ansible.posix
          - name: ansible.windows
          - name: awx.awx
          - name: containers.podman
          - name: infra.controller_configuration
          - name: infra.ah_configuration
          - name: infra.ee_utilities
  roles:
    - infra.ee_utilities.ee_builder
...
